language: cpp
compiler:
  - gcc
  - clang

before_install:
 - sudo add-apt-repository --yes ppa:dcthomp/smtk
   # Make sure package index is up to date:
 - sudo apt-get -qq update

install:
   # Remove cmake-data package as it interferes with SMTK PPA cmake package:
 - sudo dpkg -r cmake cmake-data
   # Install build tools:
 - sudo apt-get install -yqq git cmake ninja-build
   # Set user/email so any tests we might have for developers pass
 - git config --global user.email "travis@travis-ci.org"
 - git config --global user.name "Travis CI"
 - mkdir ${HOME}/cjson-install

script:
 - mkdir ~/cjson-build && cd ~/cjson-build
 - cmake -G Ninja "-DSITE:STRING=travis-ci.org" "-DBUILDNAME:STRING=${TRAVIS_OS_NAME}-${CC}-Job.${TRAVIS_JOB_NUMBER}" -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DBUILD_SHARED_LIBS:BOOL=ON "-DCMAKE_INSTALL_PREFIX=${HOME}/cjson-install" "-DCMAKE_C_FLAGS:STRING=-Wall -Wextra" ${TRAVIS_BUILD_DIR}
 - ninja -j2 install
